# Generated by Django 5.1.4 on 2025-01-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0002_daha_öge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daha_öge',
            name='güncelemeler',
        ),
        migrations.AddField(
            model_name='daha_öge',
            name='sorular',
            field=models.TextField(default='Çok yakında...'),
        ),
        migrations.AlterField(
            model_name='daha_öge',
            name='yenilik',
            field=models.TextField(max_length=100),
        ),
    ]
