# Generated by Django 5.1.4 on 2025-01-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0003_remove_daha_öge_güncelemeler_daha_öge_sorular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='daha_sorular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorular', models.TextField(default='Çok yakında...')),
            ],
        ),
        migrations.CreateModel(
            name='daha_yenilik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yenilik', models.TextField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='daha_öge',
        ),
    ]
